"""empty message

Revision ID: 162c942dc4c9
Revises: 6f499b074f3e
Create Date: 2026-06-01 10:06:15.191368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162c942dc4c9'
down_revision = '6f499b074f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dethi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oj', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dethi', schema=None) as batch_op:
        batch_op.drop_column('oj')

    # ### end Alembic commands ###
