"""empty message

Revision ID: 652f1c609500
Revises: 162c942dc4c9
Create Date: 2026-06-05 16:17:34.792248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652f1c609500'
down_revision = '162c942dc4c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('last_visit', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitor_session')
    # ### end Alembic commands ###
