"""empty message

Revision ID: 6f499b074f3e
Revises: b1aa1ac61194
Create Date: 2026-05-27 22:00:39.860435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f499b074f3e'
down_revision = 'b1aa1ac61194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dethi', schema=None) as batch_op:
        batch_op.drop_constraint('dethi_link_fkey', type_='foreignkey')
        batch_op.drop_column('link')

    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dethi_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'dethi', ['dethi_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dethi_id')

    with op.batch_alter_table('dethi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('dethi_link_fkey', 'link', ['link'], ['id'])

    # ### end Alembic commands ###
