"""empty message

Revision ID: b1aa1ac61194
Revises: c0700d39449f
Create Date: 2026-05-25 16:31:03.186729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1aa1ac61194'
down_revision = 'c0700d39449f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dethi', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dethi', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
