"""empty message

Revision ID: c0700d39449f
Revises: f76820a6f0cd
Create Date: 2026-05-25 15:55:07.194716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0700d39449f'
down_revision = 'f76820a6f0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dethi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dethi', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
